version: '3'
services:
  app:
    build: .
    container_name: web-api-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_PASSWORD=gev56poison"
      - "POSTGRES_URL=jdbc:postgresql://postgres:5432/test_akvelon"
    networks:
      - cloud
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test_akvelon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gev56poison
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cloud
networks:
  cloud:
volumes:
  pgdata: